### ISSUE TITLE
An illegal memory access was encountered

### ISSUE THREAD

**Issue by Bohuaw** [AIR-DISCOVER/LODE#1]
Thank you for your awsome job!
I have a question to ask you.
When I try to train the module, I have encountered an illegal memory access error, the detail is:
0%|                                                                                                                                                                                      | 0/3826000 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "main_sc.py", line 720, in <module>
    main()
  File "main_sc.py", line 712, in main
    train(opt, config, expr_path)
  File "main_sc.py", line 401, in train
    train_pipeline(D_model=D_model, G_model=G_model, \
  File "main_sc.py", line 307, in train_pipeline
    total_steps, train_losses = train_single_epoch(D_model, G_model, model_params, \
  File "main_sc.py", line 203, in train_single_epoch
    loss.backward()
  File "/opt/conda/envs/py38t191/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/envs/py38t191/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

It just happened when I try to train a model, but when I eval it, there is nothing wrong.
My env is CUDA 11.1, Pytorch 1.9.1, ME 0.5.4

**Comment by Philipflyg** [comment]
Thank you for your interest in our work！
Sorry for the late reply. But i haven't encountered this error. It seems an error related to CUDA and Pytorch. Maybe you can try to downgrade the pytorch version to 1.8.
