### ISSUE TITLE
voxel_path

### ISSUE THREAD

**Issue by Zhangjyhhh** [AIR-DISCOVER/LODE#4]
hello, thanks for your excellent works!!!!!!! I met some issue,so what is the voxel_path contain?
```shell
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 main_sc.py --task=visualize --experiment_name=00
00
The model directory ./logs/00 exists. Overwrite? (y/n)y
Traceback (most recent call last):
  File "main_sc.py", line 718, in <module>
    main()
  File "main_sc.py", line 714, in main
    visualize(opt, config, expr_path)
  File "main_sc.py", line 604, in visualize
    dataset = dataio.DG_Dataset(config, split='valid')
  File "/home/jyzhang/LODE/dataio.py", line 128, in __init__
    if not os.path.exists(voxels_path): raise RuntimeError('Voxel directory missing: ' + voxels_path)
RuntimeError: Voxel directory missing: /home/jyzhang/data/sequences/00/voxels
Killing subprocess 2737
Traceback (most recent call last):
  File "/home/jyzhang/anaconda3/envs/lode/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jyzhang/anaconda3/envs/lode/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jyzhang/anaconda3/envs/lode/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/jyzhang/anaconda3/envs/lode/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/jyzhang/anaconda3/envs/lode/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jyzhang/anaconda3/envs/lode/bin/python', '-u', 'main_sc.py', '--local_rank=0', '--task=visualize', '--experiment_name=00']' returned non-zero exit status 1.

```

**Comment by Tigerold** [comment]
your dataset is incomplete，there should have a voxel folder to extract form data_odometry_voxels.zip
